"""asset names

Revision ID: 2c0d395ea773
Revises: 8db4ebb2c3ab
Create Date: 2026-09-24 13:23:02.747600
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2c0d395ea773'
down_revision: str | None = '8db4ebb2c3ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_names',
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('from_digest', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('digest')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_names')
    # ### end Alembic commands ###
