"""initial: embeddings, references, texts

Revision ID: 398308130e89
Revises: 
Create Date: 2026-09-23 16:41:02.754306
"""

from collections.abc import Sequence

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '398308130e89'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Расширения создаются ЗДЕСЬ, а не руками на стенде: без vector не
    # создаётся столбец вектора, без pg_trgm — триграммный индекс, и на чистой
    # машине миграция упала бы в середине, оставив половину схемы.
    op.execute("create extension if not exists vector")
    op.execute("create extension if not exists pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest', 'model', 'kind', name='uq_asset_embeddings_digest_model_kind')
    )
    op.create_index('ix_asset_embeddings_vector', 'asset_embeddings', ['vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.create_table('reference_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('sheet_digest', sa.String(length=64), nullable=False),
    sa.Column('image_digests', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('normalised', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['reference_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reference_texts_normalised', 'reference_texts', ['normalised'], unique=False)
    op.create_index('ix_reference_texts_trgm', 'reference_texts', ['normalised'], unique=False, postgresql_using='gin', postgresql_ops={'normalised': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reference_texts_trgm', table_name='reference_texts', postgresql_using='gin', postgresql_ops={'normalised': 'gin_trgm_ops'})
    op.drop_index('ix_reference_texts_normalised', table_name='reference_texts')
    op.drop_table('reference_texts')
    op.drop_table('reference_cards')
    op.drop_index('ix_asset_embeddings_vector', table_name='asset_embeddings', postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.drop_table('asset_embeddings')
    # ### end Alembic commands ###
