"""reference card keeps the whole work

Revision ID: 4eccbc93b30d
Revises: 398308130e89
Create Date: 2026-09-24 09:11:59.572386
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4eccbc93b30d'
down_revision: str | None = '398308130e89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_cards', sa.Column('work', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_cards', 'work')
    # ### end Alembic commands ###
