"""asset tags

Revision ID: 8db4ebb2c3ab
Revises: 4eccbc93b30d
Create Date: 2026-09-24 12:47:58.967574
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8db4ebb2c3ab'
down_revision: str | None = '4eccbc93b30d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest', 'model', 'code', name='uq_asset_tags_digest_model_code')
    )
    op.create_index('ix_asset_tags_code', 'asset_tags', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_tags_code', table_name='asset_tags')
    op.drop_table('asset_tags')
    # ### end Alembic commands ###
