


export const S: Record<string, React.CSSProperties> = {
  group: { marginBottom: 14, minWidth: 0 },
  h2: { fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.6, color: '#666', margin: '0 0 6px' },
  row: { display: 'flex', flexWrap: 'wrap', gap: 6 },
  list: { display: 'flex', flexDirection: 'column', gap: 4, width: '100%' },
  item: { display: 'flex', alignItems: 'center', gap: 6, padding: '4px 6px', borderRadius: 6, border: '1px solid #e5e7eb', cursor: 'pointer' },
  itemOn: { display: 'flex', alignItems: 'center', gap: 6, padding: '4px 6px', borderRadius: 6, border: '1px solid #2563eb', background: '#eff6ff', cursor: 'pointer' },
  itemName: { flex: 1, fontSize: 12, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  badge: { fontSize: 10, color: '#b45309', background: '#fef3c7', padding: '1px 5px', borderRadius: 4 },
  x: { border: 'none', background: 'none', cursor: 'pointer', fontSize: 16, color: '#9ca3af' },
  btn: { padding: '5px 10px', border: '1px solid #d1d5db', background: '#fff', borderRadius: 6, cursor: 'pointer' },
  btnOn: { padding: '5px 10px', border: '1px solid #111', background: '#111', color: '#fff', borderRadius: 6, cursor: 'pointer' },
  tag: { color: '#9ca3af', fontStyle: 'normal', fontSize: 11 },
  thumbs: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 6, width: '100%' },
  thumb: {
    display: 'flex', flexDirection: 'column', gap: 4, padding: 4, minWidth: 0,
    border: '1px solid #d1d5db', background: '#fff', borderRadius: 6, cursor: 'pointer',
  },
  thumbOn: {
    display: 'flex', flexDirection: 'column', gap: 4, padding: 3, minWidth: 0,
    border: '2px solid #111', background: '#f3f4f6', borderRadius: 6, cursor: 'pointer',
  },
  thumbCaption: { fontSize: 11, lineHeight: 1.2, textAlign: 'center', color: '#111' },
  findingBlocking: { display: 'flex', alignItems: 'center', gap: 6, padding: '4px 7px', borderRadius: 6, border: '1px solid #fecaca', background: '#fef2f2', width: '100%', boxSizing: 'border-box' },
  findingWarning: { display: 'flex', alignItems: 'center', gap: 6, padding: '4px 7px', borderRadius: 6, border: '1px solid #fde68a', background: '#fffbeb', width: '100%', boxSizing: 'border-box' },
  // Находка — фраза, её читают целиком: переносится, а не обрезается. Длинное
  // имя файла без пробелов внутри фразы иначе выталкивает плашку из плитки.
  findingText: { flex: 1, minWidth: 0, fontSize: 12, lineHeight: 1.35, overflowWrap: 'anywhere' },
  setProbe: { display: 'flex', alignItems: 'center', gap: 6, padding: '4px 7px', borderRadius: 6, border: '1px solid #bfdbfe', background: '#eff6ff', cursor: 'pointer', textAlign: 'left', width: '100%', boxSizing: 'border-box' },
  setArtwork: { display: 'flex', alignItems: 'center', gap: 6, padding: '4px 7px', borderRadius: 6, border: '1px solid #e5e7eb', background: '#fff', cursor: 'pointer', textAlign: 'left', width: '100%', boxSizing: 'border-box' },
  textInput: { width: '100%', padding: '5px 8px', border: '1px solid #d1d5db', borderRadius: 6, marginBottom: 6 },
  swatches: { display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 4 },
  swatch: { width: 26, height: 26, borderRadius: 5, border: 'none', cursor: 'pointer', padding: 0 },
  // «Как в оригинале»: шахматка — «без краски», как прозрачность в редакторах.
  original: { background: 'repeating-conic-gradient(#d1d5db 0 25%, #fff 0 50%) 0 0 / 10px 10px', boxShadow: 'inset 0 0 0 1px #9ca3af' },
  slider: { display: 'flex', alignItems: 'center', gap: 6, width: '100%', marginBottom: 2 },
  sliderValue: { fontSize: 11, color: '#6b7280', width: 38, textAlign: 'right' },
  num: { display: 'flex', alignItems: 'center', gap: 6, width: '100%', marginBottom: 4 },
  numLabel: { flex: 1, fontSize: 12, color: '#374151' },
  numUnit: { fontSize: 12, color: '#9ca3af', width: 26 },
  input: { width: 74, padding: '3px 6px', border: '1px solid #d1d5db', borderRadius: 5 },
  found: {
    marginTop: 10,
    padding: 12,
    border: '1px solid #c7d2fe',
    background: '#eef2ff',
    borderRadius: 8,
    maxWidth: 620,
    fontSize: 13,
  },
  foundHead: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  foundRow: { display: 'flex', gap: 10, alignItems: 'center', marginTop: 8 },
  foundThumb: {
    width: 56,
    height: 56,
    objectFit: 'contain',
    background: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: 6,
  },
  gradeTable: { fontSize: 12, borderCollapse: 'collapse', width: '100%' },
  gradeRowOn: { background: '#eff6ff', fontWeight: 600 },
  manual: { fontSize: 11, color: '#b45309' },
  tags: { display: 'flex', flexWrap: 'wrap', gap: 3, width: '100%' },
  name: { fontSize: 11, fontWeight: 600, background: '#ecfdf5', color: '#065f46', padding: '1px 6px', borderRadius: 4 },
  nameInherited: { fontSize: 11, fontWeight: 600, background: '#fffbeb', color: '#92400e', padding: '1px 6px', borderRadius: 4 },
  nameSource: { fontWeight: 400, opacity: 0.8 },
  tagChip: { fontSize: 10, background: '#eef2ff', color: '#3730a3', padding: '1px 5px', borderRadius: 4 },
  tagScore: { color: '#818cf8' },
  tagWeak: { fontSize: 10, background: '#f5f5f5', color: '#6b7280', padding: '1px 5px', borderRadius: 4 },
  tagMore: { fontSize: 10, border: 'none', background: 'none', color: '#4f46e5', cursor: 'pointer', padding: '1px 3px' },
  warn: { color: '#b45309', fontSize: 13, lineHeight: 1.4, maxWidth: 620 },
  dim: { color: '#666', fontSize: 12, margin: '4px 0 0', lineHeight: 1.4 },
}
